iQMC Refactor
CEMeNT-PSAAP/MCDC pull request #204
Opened 2024-06-18 01:39 UTC by spasmann

This PR includes two significant changes:
1) All of the iQMC functions in both `loop.py` and `kernel.py` have been moved into `iqmc_loop.py` and `iqmc_kernel.py` inside of an `iqmc/` subfolder. Additionally, iQMC now calls it's own `loop_source`, `loop_partcile`, and `step_particle` functions. These changes are intended to reduce the complexity in the primary MCDC `loop` and `kernel` functions - most embedded iQMC conditional statements and loops have been removed (except for copying the `P["iqmc"]["w"]` because there is still only one particle type). This should also increase readability for both Monte Carlo and iQMC functions. 

2) The Scipy low-discrepency sequences have been removed and custom Halton sequences were added. `halton()` is the standard Halton sequence that is currently used for all iQMC simulations. `rhalton()` is the randomized-Halton sequence which will be used in a forth-coming batching method PR. This removes the dependence for `scipy`.

2024-06-22 19:31 UTC, jpmorgan98 commented
Really cool changes! IF/when we want to port iqmc to GPUs will this make that more difficult as we have more independent source files?

 I will run the GPU tests to ensure they still compile with all these changes and then merge

2024-06-22 19:42 UTC, jpmorgan98 commented
Also just so I understand it every iQMC function now uses the Halton sequence, right? Therefore it's no longer a togglable option with no need for `input_.py` documentation?

2024-06-22 19:53 UTC, jpmorgan98 requested changes
Just a few odds and ends mostly adding some spyder autodoc strings and adding some other seemingly important doc strings, if I get bored this weekend I will try and do a few of them myself. Thanks sam!!!

2024-06-22 19:53 UTC, jpmorgan98 commented on mcdc/iqmc/iqmc_kernel.py
> +#!/usr/bin/env python3
Please remove these Spyder docstrings

2024-06-22 19:53 UTC, jpmorgan98 commented on mcdc/iqmc/iqmc_kernel.py
> +def rhalton(N, dim, seed=12345, skip=0):
Could you add some doc strings here? It doesn't need to be as robust as the input deck. The halton sequence seems to be undergriding iQMC so it seems mildly important to me but lmk

2024-06-22 19:53 UTC, jpmorgan98 commented on mcdc/iqmc/iqmc_loop.py
> +#!/usr/bin/env python3
Again please remove spyder doc strings

2024-06-22 21:08 UTC, ilhamv commented
Thanks, Sam.Does the refactor solve the issue in the CSG PR?Sent from my iPhoneOn Jun 22, 2024, at 12:54 PM, Joanna Piper Morgan ***@***.***> wrote:﻿
@jpmorgan98 requested changes on this pull request.

Just a few odds and ends mostly adding some spyder autodoc strings and adding some other seemingly important doc strings, if I get bored this weekend I will try and do a few of them myself. Thanks sam!!!

In mcdc/iqmc/iqmc_kernel.py:
> @@ -0,0 +1,714 @@
+#!/usr/bin/env python3

Please remove these Spyder docstrings



In mcdc/iqmc/iqmc_kernel.py:
> +    N, dim = mcdc["technique"]["iqmc"]["lds"].shape
+    N_start = mcdc["mpi_work_start"]
+    mcdc["technique"]["iqmc"]["lds"] = halton(N, dim, skip=N_start)
+
+
***@***.***("iQMC")
+def scramble_LDS(mcdc):
+    # TODO: use MCDC seed system
+    seed_batch = np.random.randint(1000, 1000000)
+    N, dim = mcdc["technique"]["iqmc"]["lds"].shape
+    N_start = mcdc["mpi_work_start"]
+    mcdc["technique"]["iqmc"]["lds"] = rhalton(N, dim, seed=seed_batch, skip=N_start)
+
+
***@***.***("iQMC")
+def rhalton(N, dim, seed=12345, skip=0):

Could you add some doc strings here? It doesn't need to be as robust as the input deck. The halton sequence seems to be undergriding iQMC so it seems mildly important to me but lmk



In mcdc/iqmc/iqmc_loop.py:
> @@ -0,0 +1,403 @@
+#!/usr/bin/env python3

Again please remove spyder doc strings

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-07-02 01:36 UTC, jpmorgan98 commented
Passed GPU tests

2024-07-02 01:37 UTC, merged